package org.example.screen.transfer;

import java.time.LocalDateTime;

import static org.example.Main.scanner;
import static org.example.Main.transferModel;
import static org.example.components.MessageComponent.showErrorMessage;
import static org.example.components.MessageComponent.showTransferInputReferenceScreenMessage;
import static org.example.util.NumberUtil.generateRandomSixDigitNumber;
import static org.example.util.NumberUtil.isAStringNumber;
import static org.example.util.SystemUtil.println;

public class TransferInputReferenceScreen {
    public void show() {
        while (true) {
            var referenceNumber = generateRandomSixDigitNumber();

            showTransferInputReferenceScreenMessage();
            println("Reference Number (This is an autogenerated random 6 digits number)");
            println(referenceNumber.toString());
            println("Press enter to continue");

            scanner.nextLine();

            if (referenceNumber.toString().isEmpty()) {
                showErrorMessage("Invalid Reference Number");
                continue;
            }

            if (!isAStringNumber(referenceNumber.toString())) {
                showErrorMessage("Invalid Reference Number");
                continue;
            }

            transferModel.setReference(referenceNumber);
            transferModel.setDateTime(LocalDateTime.now());
            new TransferConfirmationScreen().show();
            return;
        }
    }
}
